name: optisigns-onboarding
region: nyc

# Routing configuration
ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: backend
    - match:
        path:
          prefix: /
      component:
        name: frontend

services:
  # Backend API Service
  - name: backend
    source_dir: backend
    github:
      repo: kathrynbuckley-spec/optisigns-onboarding
      branch: main
      deploy_on_push: true

    dockerfile_path: Dockerfile

    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 8080

    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        value: d0638e25d76e58b29c1fb63f32b49d949109916c488fb62e4b8486f8f16657047a72663a8a622d6069aa524c4847e0dd2e3567e3a8592e634db338effc979dfb
        type: SECRET
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: MONGODB_URI
        value: mongodb+srv://kathrynbuckley_db_user:KKwx8mSwKDXTKmSL@cluster0.f7fzwx8.mongodb.net/optisigns-onboarding?retryWrites=true&w=majority&appName=Cluster0
        type: SECRET
      - key: CORS_ORIGIN
        value: ${APP_URL}

    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3

  # Frontend Static Site
  - name: frontend
    source_dir: frontend
    github:
      repo: kathrynbuckley-spec/optisigns-onboarding
      branch: main
      deploy_on_push: true

    dockerfile_path: Dockerfile

    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 8080

    envs:
      - key: API_URL
        value: ${APP_URL}/api
